### ISSUE TITLE
skia_canvas 0.5.2 fails on Big Sur, requires Monterey

### ISSUE THREAD

**Issue by backspaces** [DjDeveloperr/skia_canvas#55]
On my elderly iMac (late 2014) running  Big Sur macOS 11 (November 19, 2020), skia_canvas 0.5.2  does not import correctly, creating the error below.

```
deno  --unstable repl -A
Deno 1.33.1
exit using ctrl+d, ctrl+c, or close()
> import * as skiaCanvas from 'https://deno.land/x/skia_canvas@0.5.2/mod.ts'
Uncaught Error: Could not open library: Could not open library: dlopen(/Users/owen/Library/Caches/deno/plug/https/github.com/dde09b5bbcf801e9d3dbb0bf6276f9d048d6643f6b34855bc184ebffa990fd30.dylib, 5): Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
  Referenced from: /Users/owen/Library/Caches/deno/plug/https/github.com/dde09b5bbcf801e9d3dbb0bf6276f9d048d6643f6b34855bc184ebffa990fd30.dylib (which was built for Mac OS X 12.6)
  Expected in: /usr/lib/libc++.1.dylib

    at new DynamicLibrary (ext:deno_ffi/00_ffi.js:440:46)
    at Object.dlopen (ext:deno_ffi/00_ffi.js:577:10)
    at dlopen (https://deno.land/x/plug@1.0.0-rc.3/mod.ts:145:15)
    at eventLoopTick (ext:core/01_core.js:166:11)
    at async https://deno.land/x/skia_canvas@0.5.2/src/ffi.ts:961:10
```

If indeed this is generally true that Monterey (osx 12 October 25, 2021) or later is required, this seems to limit skia_canvas to a smaller community.

Could we somehow widen the systems on which skia_canvas runs?

**Comment by DjDeveloperr** [comment]
I'll look into changing the minimum macOS version required to Big Sur.
