### ISSUE TITLE
`GLIBCXX_3.4.32' not found

### ISSUE THREAD

**Issue by alexgleason** [DjDeveloperr/skia_canvas#66]
```
deno run -A --unstable-ffi captcha.ts
error: Uncaught (in promise) Error: Could not open library: Could not open library: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /home/alex/.cache/deno/plug/https/github.com/ca5f22309759238252351f9be046c2fe0145354ddfb7f7a85ff783475f26edda.so)
  return Deno.dlopen<S>(await download(options), symbols as any);
              ^
    at new DynamicLibrary (ext:deno_ffi/00_ffi.js:454:42)
    at Object.dlopen (ext:deno_ffi/00_ffi.js:558:10)
    at dlopen (https://jsr.io/@denosaurs/plug/1.0.5/mod.ts:155:15)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async https://jsr.io/@gfx/canvas/0.5.6/src/ffi.ts:966:10
```

I am on Pop!_OS 22.04 LTS

I have a lot of versions of glibc++ except for the one it wants:

```
strings /lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX

GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_3.4.26
GLIBCXX_3.4.27
GLIBCXX_3.4.28
GLIBCXX_3.4.29
GLIBCXX_3.4.30
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

**Comment by DjDeveloperr** [comment]
Looks like it requires a newer one, probably because of the CI machine release was built on.
